Issue 3 user can view recipe information
OSAdams/entree-finder pull request #10
Opened 2022-07-05 01:44 UTC by OSAdams

![ajax-project-issue-3](https://user-images.githubusercontent.com/76730244/177233382-d5117766-12b6-4c7f-af41-2405e5a82569.gif)

2022-07-06 02:22 UTC, TimelikeClosure requested changes

2022-07-06 02:22 UTC, TimelikeClosure commented on css/layout.css
> +div.feature-components {
Generally, when you select a class, you don't need to include its tag name. It makes it easier down-the-road if you need to change HTML semantics.

2022-07-06 02:22 UTC, TimelikeClosure commented on css/styles.css
> +  height: 9%;
I recommend sizing a header's height based on its content, not based on its parent's height.

2022-07-06 02:22 UTC, TimelikeClosure commented on css/styles.css
> +  font-size: 30px;
Use `rem` for font sizes: https://lfz-lms.herokuapp.com/code-guides/Learning-Fuze/curriculum/effective-css

2022-07-06 02:22 UTC, TimelikeClosure commented on css/styles.css
> +  overflow-y: scroll;
Most of the time, `auto` is more useful than `scroll`, since it only shows a scrollbar if there is, in fact, scrolling.

2022-07-06 02:22 UTC, TimelikeClosure commented on js/main.js
> +}
For a utility function like this that takes more than three or so parameters, you may want to combine the optional ones into a single `options` object parameter with corresponding key names (`options.className`, `options.id`, etc.). Also, what's the difference between `title` and `duration` here?

2022-07-18 23:39 UTC, OSAdams commented
![vegan-recipes-render-recipe-feature](https://user-images.githubusercontent.com/76730244/179634618-eee2071f-b4a9-4505-8209-6580c1540df1.gif)

2022-07-19 16:45 UTC, merged

2022-07-20 02:20 UTC, TimelikeClosure reviewed
@OSAdams Your 3rd feature is approved!